### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by RohithYogi** [sujitkc/statechart-verification#2]
location "/statechart-verification/src/dfa/stablcfg/CFG.java" has an import error 
Line 10: correction import program.IProgram to import program.Program
There is no file named IProgram but instead, this was Program.

**Comment by sujitkc** [comment]
Dear Rohith,

Thanks for pointing this out. That import was redundant. I have removed it and have recommitted. Please pick up the version which I commit just a few minutes back.

Regards,
Sujit
